name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Run TestCafe Tests
      uses: DevExpress/testcafe-action@latest
      continue-on-error: true
      with:
        args: chromium:headless tests/**/* -s takeOnFails=true --reporter json:report.json,list --hostname localhost --skip-js-errors

    - name: Upload test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-artifacts
        path: |
          screenshots
          report.json

  process-artifacts:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Download test artifacts
      uses: actions/download-artifact@v2
      with:
        name: test-artifacts

    - name: Install packages from .github/jira-importer/package.json
      run: npm install --prefix .github/jira-importer

    - name: Run custom tool to process artifacts
      run: |
        node .github/jira-importer/app.js
      env:
        CI_BUILDS_DIR: ${{ github.workspace }}
        JIRA_PROJECT_KEY: DEV
        JIRA_BASE_URL: https://spenx.atlassian.net/
        JIRA_USER: im@spenxy.com
        JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
        XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
